[option]
exclude_paths = ["build.*", "sw/.*", ".sv.tpl$", "vendor/.*"]

[textrules]
header_copyright = false
style_directives = true
style_semicolon = true
style_textwidth = false

[syntaxrules]
action_block_with_side_effect = true
blocking_assignment_in_always_at_edge = true
blocking_assignment_in_always_ff = true
blocking_assignment_in_always_latch = true
case_default = true
default_nettype_none = true
enum_with_type = true
eventlist_comma_always_ff = false
eventlist_or = true
explicit_case_default = true
explicit_if_else = false
function_same_as_system_function = true
function_with_automatic = true
general_always_level_sensitive = true
general_always_no_edge = true
genvar_declaration_in_loop = true
genvar_declaration_out_loop = false
implicit_case_default = false
inout_with_tri = true
input_with_var = true
interface_identifier_matches_filename = true
interface_port_with_modport = true
keyword_forbidden_always = true
keyword_forbidden_always_comb = false
keyword_forbidden_always_ff = false
keyword_forbidden_always_latch = false
keyword_forbidden_generate = true
keyword_forbidden_logic = false
keyword_forbidden_priority = true
keyword_forbidden_unique = true
keyword_forbidden_unique0 = true
keyword_forbidden_wire_reg = true
keyword_required_generate = false
localparam_explicit_type = true
localparam_type_twostate = true
loop_statement_in_always_comb = true
loop_statement_in_always_ff = true
loop_statement_in_always_latch = true
loop_variable_declaration = true
module_ansi_forbidden = false
module_identifier_matches_filename = true
module_nonansi_forbidden = true
multiline_for_begin = true
multiline_if_begin = true
non_blocking_assignment_in_always_comb = true
non_blocking_assignment_in_always_no_edge = true
operator_case_equality = true
operator_incdec = false
operator_self_assignment = false
output_with_var = true
package_identifier_matches_filename = true
package_item_not_in_package = true
parameter_default_value = true
parameter_explicit_type = true
parameter_in_generate = true
parameter_in_package = true
parameter_type_twostate = true
procedural_continuous_assignment = true
program_identifier_matches_filename = true
sequential_block_in_always_comb = true
sequential_block_in_always_ff = true
sequential_block_in_always_latch = true
unpacked_array = true

generate_case_with_label = true
generate_for_with_label = true
generate_if_with_label = true

lowercamelcase_interface = false
lowercamelcase_module = false
lowercamelcase_package = false

prefix_inout = true
prefix_input = true
prefix_instance = true
prefix_interface = false
prefix_module = false
prefix_output = true
prefix_package = false

re_forbidden_assert = false
re_forbidden_assert_property = false
re_forbidden_checker = false
re_forbidden_class = false
re_forbidden_function = false
re_forbidden_generateblock = false
re_forbidden_genvar = false
re_forbidden_instance = false
re_forbidden_interface = false
re_forbidden_localparam = false
re_forbidden_modport = false
re_forbidden_module_ansi = false
re_forbidden_module_nonansi = false
re_forbidden_package = false
re_forbidden_parameter = false
re_forbidden_port_inout = false
re_forbidden_port_input = false
re_forbidden_port_interface = false
re_forbidden_port_output = false
re_forbidden_port_ref = false
re_forbidden_program = false
re_forbidden_property = false
re_forbidden_sequence = false
re_forbidden_task = false
re_forbidden_var_class = false
re_forbidden_var_classmethod = false

re_required_assert = false
re_required_assert_property = false
re_required_checker = false
re_required_class = false
re_required_function = false
re_required_generateblock = false
re_required_genvar = false
re_required_instance = false
re_required_interface = false
re_required_localparam = false
re_required_modport = false
re_required_module_ansi = false
re_required_module_nonansi = false
re_required_package = false
re_required_parameter = false
re_required_port_inout = false
re_required_port_input = false
re_required_port_interface = false
re_required_port_output = false
re_required_port_ref = false
re_required_program = false
re_required_property = false
re_required_sequence = false
re_required_task = false
re_required_var_class = false
re_required_var_classmethod = false

uppercamelcase_interface = true
uppercamelcase_module = true
uppercamelcase_package = true

style_commaleading = false
style_indent = false
style_keyword_0or1space = true
style_keyword_0space = true
style_keyword_1or2space = true
style_keyword_1space = true
style_keyword_construct = true
style_keyword_datatype = true
style_keyword_end = true
style_keyword_maybelabel = true
style_keyword_new = true
style_keyword_newline = true
style_operator_arithmetic = true
style_operator_arithmetic_leading_space = true
style_operator_boolean = true
style_operator_boolean_leading_space = true
style_operator_integer = true
style_operator_integer_leading_space = true
style_operator_unary = true
style_trailingwhitespace = true

tab_character = false
